// <auto-generated />
using GaleriaFotos.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaleriaFotos.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240323182504_Migration Teste")]
    partial class MigrationTeste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("GaleriaFotos.Server.Models.Fotos", b =>
                {
                    b.Property<int>("FotosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FotosId");

                    b.ToTable("fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
